apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prj028-pre-logistics-shared-claim
  namespace: __KubernetesNamespace__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi