apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prj028-logistics-shared-claim
  namespace: __KubernetesNamespace__
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 2Gi