apiVersion: v1
kind: ConfigMap
metadata:
  name: __KubernetesNamespace__-nginx-conf
  namespace: __KubernetesNamespace__
data:
  nginx.conf: |
    user  nginx;
    worker_processes auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
      worker_connections 66536;
      use epoll;
      multi_accept on;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
    
      gzip on;
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    
      server {
          listen 80;
          index index.php index.html;
          error_log  /var/log/nginx/error.log;
          access_log /var/log/nginx/access.log;
          root /var/www/public;
          location ~ \.php$ {
              try_files $uri =404;
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_index index.php;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param PATH_INFO $fastcgi_path_info;
          }
          location / {
              try_files $uri $uri/ /index.php?$query_string;
              gzip_static on;
              proxy_connect_timeout 120s; 
          }
          location ~* .(jpg|jpeg|png|gif|ico)$ {
              expires 365d;
              log_not_found off;
              access_log off;
          }
          location ~* \.(?:js|css)$ {
              access_log off;
              add_header Cache-Control "public, max-age=31536000, immutable";
              try_files $uri =404;
          }
          # Para evitar cachear el manifest.json
          location /build/manifest.json {
            add_header Cache-Control "no-cache, must-revalidate";
          }
          client_max_body_size 32M;
          client_body_buffer_size 128k;
          client_header_buffer_size 1k;
          client_body_timeout 32;
          client_header_timeout 32;
          keepalive_timeout 32;
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: __KubernetesNamespace__-app-local-ini
  namespace: __KubernetesNamespace__
data:
  default.conf: |
    upload_max_filesize=40M
    post_max_size=40M
    max_input_vars = 100000
    date.timezone = "UTC"